site_name: "Documentation"
site_dir: docs-site
repo_url: "https://github.com/trinsic-id/sdk"
edit_uri: edit/main/docs/
repo_name: trinsic-id/sdk
site_url: https://ecosystems-docs-alpha.trinsic.id
nav:
  - Welcome!: index.md
  - Join the Beta: early-adopter.md
  - Ask a Question: support.md
  - Learn:
    - Introduction: learn/index.md
    - Ecosystems: learn/ecosystems.md
    - Credentials: learn/credentials.md
    - Passes: learn/passes.md
    - Wallets: learn/wallets.md
    # - Security: learn/security.md TODO
    - Underlying Tech: learn/tech.md
  - Build:
    - Trinsic CLI: cli/index.md
    - Node: node/index.md
    - C#: dotnet/index.md
    - Python: python/index.md
    # - Ruby: ruby/index.md
    # - Go: go/index.md
    # - Java: java/index.md
    # - Web: web/index.md
    # - iOS: ios/index.md
    #  - Android: android/index.mdw
  - Reference:
    - Overview: reference/index.md
    - Wallet Service: reference/services/wallet-service.md
    - Provider Service: reference/services/provider-service.md
    - Trust Registry Service: reference/services/trust-registry.md
    - Protocol Buffers: reference/proto/index.md
  - External Resources:
    - Join the Community: https://join.slack.com/t/trinsiccommunity/shared_invite/zt-pcsdy7kn-h4vtdPEpqQUlmirU8FFzSQ
    # - Roadmap: roadmap.md TODO 
    # - Changelog: changelog.md TODO
    - Github: https://github.com/trinsic-id
theme:
  name: material
  logo: _static/logo-title.svg
  favicon: _static/logo.png
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/cloud-moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: [".", "docs"]
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
custom_dir: overrides
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - _static/javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs.min.css
  - _static/extra.css

extra:
  generator: false

plugins:
  - codeinclude