[package]
name = "okapi"
version = "0.1.0"
authors = ["Jace Kandare <jace.kandare@yahoo.com>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
didcomm-grpc = { path = "../../didcomm-v2/native" }
clap = {version = "~2.27.0", features = ["yaml"]}
serde = "1.0.119"
serde_json = "1.0.60"
chrono = "0.4.19"
base64 = "0.13.0"
toml = "0.5"
dirs = "3.0"
yaml-rust = "0.3"
colored = "2"

[build-dependencies]
tonic-build = "0.4"
prost-build = "0.7"

[[bin]]
name = "okapi"
path = "src/main.rs"

[lib]
name = "okapi"
path = "src/lib.rs"
