[package]
name = "trinsic"
version = "0.1.0"
authors = ["Trinsic <support@trinsic.id>"]
edition = "2021"

[dependencies]
tonic = { version = "0.6", git = "https://github.com/hyperium/tonic", features = ["tls"] }
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-rustls = "*"
rustls-connector = "0.15"
okapi = { git ="https://github.com/trinsic-id/okapi", branch = "main" }
clap = { version = "~2", features = ["yaml"] }
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
base64 = "0.13"
toml = "0.5"
dirs = "3.0"
yaml-rust = "0.3"
colored = "2"
actix-rt = "*"
rustls = "0.20"
webpki-roots = "0.22"

[build-dependencies]
tonic-build = { version = "0.5", features = ["prost", "rustfmt"] }

[[bin]]
name = "trinsic"
path = "src/main.rs"

[lib]
name = "trinsic"
path = "src/lib.rs"
doctest = false
