name: Build Swift SDK

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_swift:
    name: Test Swift code
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, Test
        run: |
          swift build
          swift test
