name: Push to buf.build
on:
  push:
    branches:
      - main
    paths:
      - "proto/**"
      - "devops/*.py"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment:
      name: buf.build
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_BUILD_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'proto/internal'
          buf_token: ${{ secrets.BUF_BUILD_TOKEN }}

  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 3.0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protobuf plugins
        run: |
          pip install -r ./devops/requirements.txt
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Compile proto files
        run: |
          git checkout -b update-protobuf-generated-files
          python ./devops/generate_proto_files.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4