name: Ruby

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "ruby/**"
      - "proto/**"
      - ".github/workflows/*ruby*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "ruby/**"
      - "proto/**"
      - ".github/workflows/*ruby*"
      - "devops/**"

jobs:
  build-and-test-ruby:
    name: Build, Test
    runs-on: ${{ matrix.os-artifact[0] }}
    strategy:
      fail-fast: false
      matrix:
        os-artifact: [ [ubuntu-latest, linux], [windows-latest, windows], [macos-latest, macos] ]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby-version: [ '2.6', '2.7', '3.0' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Download ${{ matrix.os-artifact[0] }} binaries
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          workflow: "build-libs.yml"
          path: ./libs/${{ matrix.os-artifact[1] }}
          repo: trinsic-id/okapi
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ matrix.os-artifact[1] }}
          run_id: 1903152040  # Last scheduled build before the breaking 1.4.0 release
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          python ../devops/build_sdks.py --language=ruby
          bundle exec rake
        shell: pwsh
        working-directory: ruby
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
          RUBY_DLL_PATH: "${{ github.workspace }}/libs/${{ matrix.os-artifact[1] }}"  # Required for Ruby on Windows
          LD_LIBRARY_PATH: "${{ github.workspace }}/libs/${{ matrix.os-artifact[1] }}"
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
      - name: Upload Unit Test Results - Ruby
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name:  Ruby ${{ matrix.ruby-version }} Unit Test Results (${{ matrix.os-artifact[0] }})
          path: 'ruby/test/reports/TEST-*.xml'

  publish-test-results-ruby:
    name: Publish Test Results
    needs: build-and-test-ruby
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ruby_artifacts
      - name: Publish Test Report - Ruby
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'ruby_artifacts/**/*.xml'
          check_name: Ruby Test Report