name: Go

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "go/**"
      - "proto/**"
      - ".github/workflows/*golang*"
  push:
    branches:
      - main
    paths:
      - "go/**"
      - "proto/**"
      - ".github/workflows/*golang*"

jobs:
  build-and-test-golang:
    name: Build, Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest] # , 'macos-latest' ] disabled due to macos issues
    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          repo: trinsic-id/okapi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build and Test Golang
        run: |
          go version
          go install golang.org/x/lint/golint@latest
          go install github.com/jstemmer/go-junit-report@latest
          python ../../devops/build_sdks.py
          go build
          golint
          go test -v | go-junit-report > test_output.xml
        shell: pwsh
        working-directory: go/okapi
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/go/okapi"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/go/okapi"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/go/okapi"
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      - name: Upload Unit Test Results - Golang
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Golang Unit Test Results (${{ matrix.os }})
          path: 'go/okapi/test_output*.xml'

  publish-test-results-golang:
    name: Publish Test Results
    needs: build-and-test-golang
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: golang_artifacts
      - name: Publish Test Report - Golang
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        with:
          files: 'golang_artifacts/**/*.xml'
          check_name: Golang Test Report
