name: Golang (build)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "go/**"
      - "proto/**"
      - ".github/workflows/*golang*"
  push:
    branches:
      - main

jobs:
  test_go:
    name: Test Go code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux
          - os: windows-latest
            artifact_name: windows-gnu
          - os: macos-latest
            artifact_name: macos
    steps:
      - uses: actions/checkout@v2
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          repo: trinsic-id/okapi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Display Golang version
        run: |
          go version
          go install golang.org/x/lint/golint@latest
          go install github.com/jstemmer/go-junit-report@latest
      - name: Build, Test, Pack
        run: |
          ./devops/BuildGolang.ps1 -GitTag ${{ github.ref }} -TestOutput "test_output_${{ matrix.os }}.xml" -ArtifactName "${{ matrix.artifact_name }}"
        shell: pwsh
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/go/services"
          DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/go/services"
          DYLD_LIBRARY_PATH: "${{ github.workspace }}/go/services"
          CGO_LDFLAGS: "-L${{ github.workspace }}/go/services"
          CGO_CFLAGS: "-I${{ github.workspace }}/go/services"
          TEST_SERVER_ENDPOINT: staging-internal.trinsic.cloud
          TEST_SERVER_PORT: 443
          TEST_SERVER_USE_TLS: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: ./go/services/test_output*.xml
          fail_on_failure: true
