name: ".NET"

on:
  workflow_call:
  pull_request:
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
      - "devops/**"
  push:
    branches:
      - main
    paths:
      - "dotnet/**"
      - "proto/**"
      - ".github/workflows/*dotnet*"
      - "devops/**"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: |
          dotnet workload install ios
          dotnet restore
          dotnet build -c Release -f net6.0 -p:IsBrowser=true ./Trinsic
          dotnet build -c Release
          dotnet test -c Release -v n /p:CollectCoverage=true /p:CoverletOutput=./ /p:CoverletOutputFormat=cobertura
        working-directory: ./dotnet
        env:
          TEST_SERVER_ENDPOINT: ${{ secrets.TEST_SERVER_ENDPOINT }}
          TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          TEST_SERVER_USE_TLS: ${{ secrets.TEST_SERVER_USE_TLS }}
