name: Ruby Gem

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build + Publish Ruby
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.76.0
        with:
          ruby-version: 2.7
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.14.0
        with:
          workflow: "build-libs.yml"
          path: ./libs
          branch: main
          repo: trinsic-id/okapi
      - name: Install dependencies
        run: |
          bundle config set rubygems.pkg.github.com ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
        working-directory: ruby
      - name: Build and run tests
        run: ./devops/BuildRuby.ps1 -GitTag ${{ github.ref }}
        shell: pwsh
        env:
          TRINSIC_SERVER_ADDRESS: http://pr-development.centralus.azurecontainer.io:5000/
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/trinsic-id *.gem
        working-directory: ruby
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"

      # - name: Publish to RubyGems
        # run: |
          # mkdir -p $HOME/.gem
          # touch $HOME/.gem/credentials
          # chmod 0600 $HOME/.gem/credentials
          # printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          # gem build *.gemspec
          # gem push *.gem
        # env:
          # GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"