name: "Rust (release)"

on:
  workflow_dispatch:
  release:
    types: [published, prereleased]
  pull_request:

jobs:
  homebrew:
    runs-on: macos-latest
    environment: homebrew
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v1
      - name: Build CLI
        run: |
          rustup install nightly
          rustup default nightly
          rustup component add rustfmt
          cargo build --release
          cargo test --release
      - name: Codesign Binary File
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_DEVELOPER_ID_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_IDENTITY: ${{ MACOS_DEVELOPER_ID_CERTIFICATE_IDENTITY }}
        run: |
          $env:TMP_PASS = [Guid]::NewGuid().ToString()
          [System.IO.File]::WriteAllBytes([System.IO.Path]::Combine($pwd.Path, "certificate.p12"), [System.Convert]::FromBase64String("$env:MACOS_CERTIFICATE"))
          security create-keychain -p $env:TMP_PASS build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $env:TMP_PASS build.keychain
          security list-keychains -s build.keychain
          security import certificate.p12 -k build.keychain -P $env:MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $env:TMP_PASS build.keychain
          /usr/bin/codesign --force -s $env:MACOS_CERTIFICATE_IDENTITY trinsic -v
        shell: pwsh
        working-directory: ./cli/target/release

      - name: Generate Archive Version
        run: |
          $json = Invoke-WebRequest 'https://api.github.com/repos/trinsic-id/okapi/releases/latest'
          echo "TAG_NAME=$json.tag_name" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - name: Build Archive
        run: |
          $file = trinsic_cli_$env:TAG_NAME_macos_x86_64.tar.gz
          tar czf $file --directory=./target/release/ trinsic
          echo "ARTIFACT_FILE=$file" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - uses: svenstaro/upload-release-action@v2
        name: Upload Archive
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACT_FILE }}
          asset_name: ${{ env.ARTIFACT_FILE }}
          tag: ${{ env.TAG_NAME }}
          overwrite: true
          body: "Trinsic CLI for MacOS"




