name: Release Python SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version - PEP440 compliant [N!]N(.N)*[{a|b|rc}N][.postN][.devN]'
        required: true
        default: ' '
  release:
    types: [ published ]
  push:
    branches:
      - main

jobs:
  release_testpypi:
    name: Python Package deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build, Test, Pack
        run: ./devops/BuildPython.ps1 -GitTag "${{ github.ref }}" -PackageVersion "${{ github.event.inputs.version }}"
        shell: pwsh
      - name: Push packages to release
        if: |
          (github.event_name == 'release' &&
          github.event.action == 'published')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./python/dist/*
          file_glob: true
          asset_name: "python"
          tag: ${{ github.ref }}
          overwrite: true
          body: "Python SDK package"
      - name: Publish distribution ðŸ“¦ to PyPI
        if: |
          (github.event_name == 'release' &&
          github.event.action == 'published') ||
          github.event.inputs.version != ''
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./python/dist